Player
forma-web/forma-media-frontend pull request #3
Opened 2023-01-12 20:45 UTC by RomaFedoro

Done progress bar, control buttons, key events and animation

2023-01-12 21:17 UTC, robonen commented on src/composables/usePlayer.ts
> +    toggleMute();
`e.preventDefault();` 😉

2023-01-12 21:20 UTC, robonen requested changes
Добавь preventDefault

2023-01-13 07:05 UTC, RomaFedoro commented on src/composables/usePlayer.ts
> +    toggleMute();
💩

2023-01-13 09:56 UTC, robonen approved these changes

2023-01-13 09:57 UTC, merged